# Generated by Django 4.2.1 on 2023-09-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=20)),
                ('hobbies', models.TextField(max_length=20)),
            ],
        ),
    ]
